CREATE TABLE BMN_ACCOUNT_TYPE (
	ACCOUNT_TYPE_ID INT NOT NULL
	,ACCOUNT_TYPE_TEXT NVARCHAR(1024)
	,SOFT_DELETED NVARCHAR (1) NULL
	,CREATE_TS DATETIME
	,UPDATE_TS DATETIME
	,CONSTRAINT PK_ACCOUNT_TYPE PRIMARY KEY (ACCOUNT_TYPE_ID)
	)

	ALTER TABLE BMN_ACCOUNT_TYPE ADD CONSTRAINT ACCOUNT_TYPE_CREATE_TS DEFAULT SYSDATETIME() FOR CREATE_TS;

	ALTER TABLE BMN_ACCOUNT_TYPE ADD CONSTRAINT ACCOUNT_TYPE_UPDATE_TS DEFAULT SYSDATETIME() FOR UPDATE_TS;

	ALTER TABLE BMN_ACCOUNT_TYPE ADD CONSTRAINT ACCOUNT_TYPE_SOFT_DELETE DEFAULT 'N' for SOFT_DELETED;