CREATE TABLE BMN_ATTACHMENT (
	ATTACHMENT_ID INT NOT NULL
	,TXN_ID INT NOT NULL
	,IMG VARBINARY(MAX) NULL
	,CREATE_TS DATETIME
	,UPDATE_TS DATETIME
	,CONSTRAINT PK_ATTACHMENT PRIMARY KEY (ATTACHMENT_ID)
	);

	ALTER TABLE BMN_ATTACHMENT ADD CONSTRAINT ATTACHMENT_CREATE_TS DEFAULT SYSDATETIME() FOR CREATE_TS;

	ALTER TABLE BMN_ATTACHMENT ADD CONSTRAINT ATTACHMENT_UPDATE_TS DEFAULT SYSDATETIME() FOR UPDATE_TS;