CREATE TABLE BMN_TRANSACTION (
	TXN_ID INT NOT NULL
	,CATEGORY_ID INT NOT NULL
	,SUB_CATEGORY_ID INT NOT NULL
	,AMOUNT DECIMAL(10, 2) NOT NULL
	,DIRECTION NVARCHAR(3) NOT NULL
	,COMMENT NVARCHAR(MAX) NULL
	,ATTACHMENT_ID INT NOT NULL
	,ACCOUNT_ID INT NOT NULL
	,CREATE_TS DATETIME
	,UPDATE_TS DATETIME
	,CONSTRAINT PK_TRANSACTION PRIMARY KEY (TXN_ID)
	)

	ALTER TABLE BMN_TRANSACTION ADD CONSTRAINT TRANSACTION_CREATE_TS DEFAULT SYSDATETIME() FOR CREATE_TS;

	ALTER TABLE BMN_TRANSACTION ADD CONSTRAINT TRANSACTION_UPDATE_TS DEFAULT SYSDATETIME() FOR UPDATE_TS;


