CREATE TABLE BMN_CATEGORY (
	CATEGORY_ID INT NOT NULL
	,CATEGORY_NAME NVARCHAR(1024) NOT NULL
	,SOFT_DELETED NVARCHAR (1) NULL
	,CREATE_TS DATETIME
	,UPDATE_TS DATETIME
	,CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID)
	);

	ALTER TABLE BMN_CATEGORY ADD CONSTRAINT CATEGORY_CREATE_TS DEFAULT SYSDATETIME() for CREATE_TS;

	ALTER TABLE BMN_CATEGORY ADD CONSTRAINT CATEGORY_UPDATE_TS DEFAULT SYSDATETIME() for UPDATE_TS;

	ALTER TABLE BMN_CATEGORY ADD CONSTRAINT CATEGORY_SOFT_DELETE DEFAULT 'N' for SOFT_DELETED;